In [1]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [1]:
#python for machine learning


In [28]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression



In [29]:
X,y = np.arange(10).reshape((5,2)), range(5)

In [30]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
list(y)

[0, 1, 2, 3, 4]

In [32]:
X_train, x_test , y_train, y_test = train_test_split(X, y, test_size=0.3)

In [33]:
X_train

array([[8, 9],
       [4, 5],
       [6, 7]])

In [34]:
y_train

[4, 2, 3]

In [35]:
x_test

array([[0, 1],
       [2, 3]])

In [25]:
y_test

[3, 4]

In [36]:
model = LinearRegression()

In [37]:
model.fit(X_train,y_train)

LinearRegression()

In [38]:
prediction = model.predict(x_test)

In [39]:
prediction

array([8.04911693e-16, 1.00000000e+00])